### ISSUE TITLE
[Feature Request]: Torrent Tracker List Configuration

### ISSUE THREAD

**Issue by MeguminSama** [ThaUnknown/miru#498]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Especially on older torrents, it can be hard to find seeders, even with DHT/PeX enabled.

### Proposed Solution

Adding an option (likely in `Settings > Torrent`) for a user to paste in custom trackers (newline separated) that get automatically added to every torrent a user watches.

For example, when I run into a torrent that doesn't have many seeders, pasting the contents of [this tracker list](https://github.com/ngosang/trackerslist/blob/master/trackers_all.txt) into the trackers list on qbittorrent often helps me find more seeders. 

I might attempt to implement this myself if you think it would be a useful addition to the project.

**Comment by ThaUnknown** [comment]
general consensus for this is: no

miru already adds a bunch of trackers, and since it supports DHT/PeX the trackers it forcefully adds should be enough
